package fetchdata

type TaskAddFetchData struct {
	Auth     string        `json:"auth" bson:"auth"`         // only generated by bot
	Override FetchOverride `json:"override" bson:"override"` // user's info, override reactive var in fronted
	Expire   int64         `json:"expire" bson:"expire"`     // unix time in second
}
type Interval struct {
	Time int    `json:"time" bson:"time"`
	Text string `json:"text" bson:"text"` // express time interval in a sentence
}
type FetchedSettings struct {
	Interval  []Interval `json:"interval" bson:"interval"`
	PageRange [2]int     `json:"pageRange" bson:"pageRange"` // range of mercarigo.Mercari_search's page
}
type FetchOverride struct {
	Owner int64 `json:"owner" bson:"owner"` // user's qq
	Group int64 `json:"group" bson:"group"` // group that user send commands from
}
